### ISSUE TITLE
Return contributor and group data in causal GO-CAM query

### ISSUE THREAD

**Issue by dustine32** [geneontology/api-gorest-2021#11]
After switching to using the causal model query in https://github.com/geneontology/web-gocam/issues/20, @thomaspd and @tmushayahama noticed that we were no longer seeing model contributor and group data on the GO-CAM browser site:
![image](https://user-images.githubusercontent.com/2678599/194960565-0f8ca1f9-4f8a-47f1-8522-25963aff3208.png)

I see this is because these fields are not returned in the [ModelsWith2CausalMFs](https://github.com/geneontology/api-gorest-2021/blob/f83aeda7fa6b3164fffc4f3cfa57d998a7397ea6/queries/sparql-models.js#L361) query but are in the previously used [ModelList](https://github.com/geneontology/api-gorest-2021/blob/f83aeda7fa6b3164fffc4f3cfa57d998a7397ea6/queries/sparql-models.js#L15-L18) query

To fix this, we simply need to add these fields to the causal query and then regenerate the JSON files.

**Comment by dustine32** [comment]
This fix is in place and working.

**Comment by kltm** [comment]
Cheers!
