### ISSUE TITLE
Replace Barista dependencies in the GO-CAM API

### ISSUE THREAD

**Issue by kltm** [geneontology/api-gorest-2021#6]
Recently, it seems that barista is having trouble, possibly related to increased use or volume and possibly related to its use as an upstream API (a la https://github.com/geneontology/api-gorest-2021/blob/3f2e9958286a63c24cd8ce599c762e56b40f5eff/app.js#L283).

We'd like to take a look at other ways of supplying this JSON data to the API in the short run. Ideas include

1. render during pipeline and push to public location for use by API
2. load into solr and have API use that
3. other?

**Comment by kltm** [comment]
After a little discussion, I think we will likely go for the rendered JSON route as a short-term solution (and allowing us to get to the AmiGO widgets faster), while keeping the Solr-ization on the books when we start bringing in the GO-CAM API to the GO API.

**Comment by kltm** [comment]
@dustine32 Following up from the software meeting, scanning through the code, these seem to be the only instances of contact: 
`/gocam/:id/raw` uses
https://github.com/geneontology/api-gorest-2021/blob/965cba7dccb524d88586cf996ffe1e8715c92c14/app.js#L283
`/gocam/:id/activities` uses
https://github.com/geneontology/api-gorest-2021/blob/965cba7dccb524d88586cf996ffe1e8715c92c14/app.js#L302
`/gocam/:id/enriched` uses
https://github.com/geneontology/api-gorest-2021/blob/965cba7dccb524d88586cf996ffe1e8715c92c14/app.js#L334
To my eye, these all seem to be identical and seem to bypass any kind of middleware, making them easy to change. I believe simply routing these to a static location will solve any problems we're having. Can you think of any reason this might not work?

@balhoff What would be the best way to approach getting the currently returned raw JSON form out of minerva (or the noctua-models repo)? I'm assuming we don't currently have a command or CLI for this, but I'm wondering how hard it might be to add or if there might be other approaches?

**Comment by dustine32** [comment]
@kltm Thanks, I never realized the barista URLs were repeated like this!

> Can you think of any reason this might not work?

Nope, can't think of any reason changing to a static JSON endpoint wouldn't work. I'm all for this.

**Comment by kltm** [comment]
@balhoff (Bringing this up to a top-level comment for reference)
What would be the best way to approach getting the currently returned raw JSON form out of minerva (or the noctua-models repo)? I'm assuming we don't currently have a command or CLI for this, but I'm wondering how hard it might be to add or if there might be other approaches?

**Comment by balhoff** [comment]
So basically the format returned to Noctua when you request a whole model? I think it would be pretty easy to add a dump CLI command for that.

**Comment by kltm** [comment]
Okay, with Minerva and initial pipeline work out of the way (https://github.com/geneontology/minerva/issues/500), this becomes a deployment and API issue.
We now have a new product that will start becoming available (already tested on `master`):
`*/products/json/noctua-models-json.tgz`, which is currently like 80MB and contains all of the models individually in JSON. We'll want to:
- [x] deploy this to a public location as part of the pipeline or release
- [ ] change the API to point at these

**Comment by kltm** [comment]
@dustine32 For when you're back around, I believe that URLs like this now work (although not automated yet): `https://go-public.s3.amazonaws.com/files/go-cam/<GO-CAM_INTERNAL_ID>.json`. I guess all that would be needed is 1) automating getting it into S3 (maybe as part of the other JSON pipeline) and 2) changing the URLs.

**Comment by kltm** [comment]
`s3cmd -c KEYFILE --acl-public --mime-type=application/json put *.json s3://go-public/files/go-cam/`

**Comment by kltm** [comment]
Will add the above command to `issue-265-go-cam-products` once JSON tarball propagates to `release`.

**Comment by kltm** [comment]
Now testing in `issue-265-go-cam-products`.

**Comment by kltm** [comment]
@dustine32 Okay, it looks like the regular SOP running of `issue-265-go-cam-products` during the release process will now supply updated JSON files to the correct location in S3 (above). The final step we have here then is aiming the GO-CAM API at the correct location. I'm not sure if this is better to wait after the node 14 switchover or to get it done before the deadline. Either way, we can talk more about it on Thursday if we don't overlap before.

**Comment by dustine32** [comment]
@kltm Thank you! We can test this with dev instances of `agr_ui` and `api-gorest-2021` quick and then, if there aren't any issues, push it before the node 14 switchover?

**Comment by kltm** [comment]
I wouldn't argue with however you think the best way to test might be. I'm most worried about something getting messed up with mimetypes or the like.

**Comment by sierra-moxon** [comment]
the go-fastapi does not have any dependencies on barista, so removing this from that project for now.  please of course add back if there are endpoints that do use barista that need to be migrated to the new API in support of the UI.  It makes sense to me to have a step in the pipeline (python scripts potentially instead of API calls with a barista backend) that produces necessary files as artifacts without the API dependency.

**Comment by kltm** [comment]
@sierra-moxon Clarifying initial comment (https://github.com/geneontology/api-gorest-2021/issues/6#issue-1247081902), this is no longer in the merged API?

**Comment by kltm** [comment]
@sierra-moxon just confirming that the merged GO-CAM API has no barsita connections, correct?

**Comment by sierra-moxon** [comment]
Right; just Golr and RDF endpoint.

**Comment by kltm** [comment]
@sierra-moxon Great--binned!

**Comment by kltm** [comment]
This got accidentally closed in the shuffle.

**Comment by kltm** [comment]
This is a dependency for https://github.com/geneontology/wc-gocam-viz/issues/25

**Comment by kltm** [comment]
Keeping open until public deployment and they're _gone_ gone. (The reason we often have a `Clearing` state in the kanban.)

**Comment by kltm** [comment]
@sierra-moxon lapped me on this :)
