### ISSUE TITLE
Queries for "all causal models" vs "causal models by gene" results are inconsistent

### ISSUE THREAD

**Issue by dustine32** [geneontology/api-gorest-2021#9]
By inconsistent, I mean a model retrieved in the "causal models by gene" [query](https://github.com/geneontology/api-gorest-2021/blob/965cba7dccb524d88586cf996ffe1e8715c92c14/queries/sparql-gp.js#L67-L157) is not in the results from the "all causal models" [query](https://github.com/geneontology/api-gorest-2021/blob/965cba7dccb524d88586cf996ffe1e8715c92c14/queries/sparql-models.js#L322-L387). Some examples from @pgaudet:
* I would expect this one to be in: gomodel:6246724f00001921
It does show in Alliance: https://www.alliancegenome.org/gene/HGNC:20749
but when I search for gene name in the GO-CAM browser (ZDHHC20)I get 0 results.
* I would expect gomodel:60ad85f700000058 NOT to be in; there some connected activities, but these are binding, and especially, there are many unconnected activities. Interestingly, this one is NOT in the mouse Alliance Atf2 page: https://www.alliancegenome.org/gene/MGI:109349

We should ensure we get the following results that for these routes:
* `/models?causalmf=2`
  * Result: Contains both `gomodel:6246724f00001921` and `gomodel:60ad85f700000058`
* `/gp/http%3A%2F%2Fidentifiers.org%2Funiprot%2FQ5W0Z9/models?causalmf=2`
  * Result: Contains `gomodel:6246724f00001921`
* `/gp/http%3A%2F%2Fidentifiers.org%2Fmgi%2FMGI%3A109349/models?causalmf=2`
  * Result: Contains `gomodel:60ad85f700000058`

**Comment by kltm** [comment]
Until this gets binned elsewhere, since this is a data consistency issue in the pipeline, I'm binning it into QC. @pgaudet , feel free to move this wherever makes sense for us to not lose track of it.

**Comment by dustine32** [comment]
Just noticed a lot (if not all) of the causal models currently displayed on the browser site appear to have chains of the exact same relation (e.g. `-positively_regulates-> MF2 -positively_regulates->`, `-directly_provides_input_for-> MF2 -directly_provides_input_for->`) I'm thinking this may explain our first case above for [gomodel:6246724f00001921](http://noctua.geneontology.org/editor/graph/gomodel:6246724f00001921?) since it has two different causal relations in its chain:
![image](https://user-images.githubusercontent.com/2678599/194438130-d26facf7-38d1-4422-acb9-5592daf7ab71.png)
The current "all causal models" query uses the same `?causal` variable for connecting MF individuals 1, 2, and 3:
https://github.com/geneontology/api-gorest-2021/blob/965cba7dccb524d88586cf996ffe1e8715c92c14/queries/sparql-models.js#L376-L377
When I switched this to two vars `?causal1` and `?causal2`, I got our missing `gomodel:6246724f00001921` in the results. This separating of `?causal` vars is also used in the "by gene" query so that explains it correctly showing on the Alliance gene page:
https://github.com/geneontology/api-gorest-2021/blob/965cba7dccb524d88586cf996ffe1e8715c92c14/queries/sparql-gp.js#L113
https://github.com/geneontology/api-gorest-2021/blob/965cba7dccb524d88586cf996ffe1e8715c92c14/queries/sparql-gp.js#L117
And actually, those `causally_upstream_of:` lines look suspicious as the causal chain relations in our other case `gomodel:60ad85f700000058` are all `causally_upstream_of_or_within`, [parent](https://ontobee.org/ontology/RO?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002411) of `causally_upstream_of`. I think these "by gene" query lines should be changed to use `causally_upstream_of_or_within:` instead:
```
?causal1 rdfs:subPropertyOf* causally_upstream_of_or_within: .
?causal2 rdfs:subPropertyOf* causally_upstream_of_or_within: .
```
Yep. After changing to `causally_upstream_of_or_within:` I started getting `gomodel:60ad85f700000058` in "by gene" route `/gp/http%3A%2F%2Fidentifiers.org%2Fmgi%2FMGI%3A109349/models?causalmf=2`:
```
[{"gocam":"http://model.geneontology.org/60ad85f700000058","title":"Atf2 mouse"}]
```

I should test these changes more but for now I'll PR them for safe-keeping. Sorry @kltm, I didn't intend on fixing this today. It spiraled out of a question from @tmushayahama about lowering the causal chain threshold to 1.

**Comment by dustine32** [comment]
After merging #10, AWS auto-deployed the change and I confirmed that both of our test case genes (Atf2 Mmus, ZDHHC20 Hsap, Ern1 Mmus) now have their causal models displaying on the Alliance site gene pages.

We will still need to run the `issue-265-go-cam-products` Jenkins branch to get the new GO-CAM list out to the GO-CAM browser site. @kltm We can probably do this after `release` is done?

**Comment by dustine32** [comment]
This fix has been applied to the models on the GO-CAM browser site.
